version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
    - 2000:2000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
    - 8000:8501
    volumes:
      - ./frontend:/app