#THE BELOW WORKS, I.E. WHEN BUILDING THE DOCKER IMAGES WITHIN DOCKER-COMPOSE ALL WORKS WELL
# Command: docker-compose -f docker-compose-local.yml up --build -d
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
    - 2000:2000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
    - 8000:8501
    volumes:
      - ./frontend:/app
