#THE BELOW WORKS, I.E. WHEN BUILDING THE DOCKER IMAGES WITHIN DOCKER-COMPOSE ALL WORKS WELL
# Command: docker-compose -f docker-compose-local.yml up --build -d
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
    - 2000:2000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
    - 8000:8501
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: dummy_db
      POSTGRES_USER: dummy_user
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
