# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip
RUN pip3 install -v -r requirements.txt

COPY . .

EXPOSE 2000

# For FastAPI:
CMD ["uvicorn", "app_fastapi:app", "--host", "0.0.0.0", "--port", "2000"]

# For Flask:
# CMD ["python3", "-m", "flask", "--app", "app_flask.py", "run", "--host=0.0.0.0"]

# Alternatively:
# -- In this case main.py contains the routes and a call such as "uvicorn.run(app, host='0.0.0.0', port=80)"
# CMD ["python3", "main.py"]