# This workflow builds Docker images from the frontend and backend contexts and the
# corresponding Dockerfiles. After building, the images are pushed to Docker Hub
# repositories. On receiving a new image, these repositories send a POST request to
# the Azure Webhook URL, to inform Azure the application needs to be restarted using the
# newly pushed images. Azure App Service will use the docker-compose configuration file
# to take care of the configuration of the containers.

name: Building & Pushing images to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on newly pushed tags of specific format
  push:
#     branches:
#       - "main"
    tags:
      - "v*.*.*"
      - "!v*.*.*-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set up build cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1  # Alternatively, use azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Build and Push image Backend Image
      - name: Build and push Backend Image
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile.dev
          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mc_fastapi_server:${{ github.sha }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mc_fastapi_server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Build and Push image Frontend Image
      - name: Build and push Frontend Image
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.dev
          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mc_streamlit-ui:${{ github.sha }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mc_streamlit-ui:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Echo the results
      - name: Image digest
        run: |
          echo ${{ steps.docker_build_backend.outputs.digest }}
          echo ${{ steps.docker_build_frontend.outputs.digest }}
