# This workflow should update the Azure App Service application, given particular images
# in Docker Hub. It currently fails to detect the docker-compose.yml, however. The
# updating of the application after building and pushing new images to Docker Hub is now
# taken care of by a custom Webhook request send from Docker Hub to Azure App Service.

name: Deploy to Azure App Service

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # This step logs into Azure using a Service Principal Name (SPN) as an alternative to the "Publish Profile"
      - name: Azure Login with secrets.AZURE_CREDENTIALS
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2  # This action triggers an App restart in Azure App Service
        with:
          app-name: 'multi-container-app'
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/mc_streamlit-ui:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/mc_fastapi_server:${{ github.sha }}
          configuration-file: 'docker-compose.yml'

      # Echo the results
      - name: URL
        run: |
          echo ${{ steps.deploy-to-webapp.outputs }}
          echo ${{ steps.deploy-to-webapp.outputs.webapp-url }}
